- .github/workflows/lint.yaml
- doc/conf.py
- doc/index.rst
- doc/migrate.rst
- doc/whatsnew.rst
- message_ix_models/__init__.py
- message_ix_models/cli.py
- message_ix_models/util/importlib.py
- setup.cfg
With reference to https://realpython.com/python-import/
> Add MessageDataFinder for imports

- message_ix_models/data/edits/messageix-transport-core.yaml
- message_ix_models/data/edits/messageix-transport-input.yaml
This PR adds draft versions of two data description files for the EDITS project.
> Add EDITS data descriptions for MESSAGEix-Transport

- .github/workflows/lint.yaml
- doc/conf.py
- doc/repro.rst
- message_ix_models/testing.py
- message_ix_models/tests/util/test_context.py
Also add documentation describing how this works.
> Use pytest-cache in the session_context fixture

- doc/api/model.rst
- doc/api/util.rst
- doc/conf.py
- doc/pkg-data/node.rst
- doc/whatsnew.rst
- message_ix_models/model/bare.py
- message_ix_models/model/build.py
- message_ix_models/testing.py
- message_ix_models/tests/util/test_node.py
- message_ix_models/util/__init__.py
- message_ix_models/util/node.py
For use by e.g. MESSAGEix-Transport.
> Add function to adapt data from R11 to R14

- .github/pull_request_template.md
- doc/pkg-data/node.rst
- doc/repro.rst
- doc/whatsnew.rst
- message_ix_models/cli.py
- message_ix_models/testing.py
- message_ix_models/tests/test_cli.py
- message_ix_models/tests/util/test_context.py
This generalizes a script provided as a Jupyter notebook by @OFR-IIASA in iiasa/message_data#216.
**To complete**
**To review**
- See the additions to the documentation.
- Try to run the example command.
- Check that the output is as expected.
> Add testing.export_test_data()

- .github/workflows/lint.yaml
- .github/workflows/publish.yaml
- .github/workflows/pytest.yaml
- doc/api/model.rst
- doc/api/project.rst
- doc/api/testing.rst
- doc/api/util.rst
- doc/develop.rst
- doc/index.rst
- doc/repro.rst
- doc/whatsnew.rst
- message_ix_models/model/structure.py
- message_ix_models/testing.py
- message_ix_models/tests/model/test_disutility.py
- message_ix_models/tests/test_cli.py
- message_ix_models/tests/test_util.py
- message_ix_models/tests/util/test_cache.py
- message_ix_models/tests/util/test_context.py
- message_ix_models/tests/util/test_node.py
- message_ix_models/util/__init__.py
- message_ix_models/util/_convert_units.py
- message_ix_models/util/cache.py
- message_ix_models/util/common.py
- message_ix_models/util/context.py
- message_ix_models/util/node.py
- message_ix_models/util/scenarioinfo.py
- setup.cfg
This PR:
- Adds several small enhancements for use in testing
- Upstreams some utility code from message_data.
- Removes some old, deprecated code.
- Note that CI checks all pass.
> Small testing improvements

- doc/whatsnew.rst
- message_ix_models/cli.py
- message_ix_models/tests/util/test_cache.py
- message_ix_models/util/cache.py
- message_ix_models/util/common.py
- message_ix_models/util/context.py
- setup.cfg
- Adjust caching for khaeru/genno#50.
- Add a more explanatory message on the CLI when there is an ImportError internal to `message_data`; FYI @OFR-IIASA
Note that CI checks all pass.
- ~Add, expand, or update documentation.~ No change in user-facing behaviour.
> Adjust for genno 1.8

- .github/workflows/lint.yaml
- .github/workflows/pytest.yaml
- doc/api/model-build.rst
- doc/api/util.rst
- doc/whatsnew.rst
- message_ix_models/__init__.py
- message_ix_models/model/build.py
- message_ix_models/model/disutility.py
- message_ix_models/tests/test_util.py
- message_ix_models/tests/util/test_context.py
- message_ix_models/tests/util/test_scenarioinfo.py
- message_ix_models/util/__init__.py
- message_ix_models/util/common.py
- message_ix_models/util/context.py
- message_ix_models/util/node.py
- message_ix_models/util/scenarioinfo.py
Several enhancements needed for MESSAGEix-Transport code (iiasa/message_data#272).
Note that CI checks all pass.
> Merge improvements for 2021-W50

- doc/cli.rst
This PR generalizes the text and the command to add specific databases.
Closes issue/53.
**Required:** write a single sentence that describes the changes made by this PR.
- Build the documentation and look at the "Controlling CLI behaviour" page.
> Generalize text on adding a specific database

- doc/api/disutility.rst
- doc/whatsnew.rst
- message_ix_models/model/build.py
- message_ix_models/model/disutility.py
- message_ix_models/tests/model/test_disutility.py
Addresses #45, specifically https://github.com/iiasa/message-ix-models/issues/45#issuecomment-1058107571 and https://github.com/iiasa/message-ix-models/issues/45#issuecomment-1059039078
FYI @Jihoon @volker-krey
- Try the code against an Oracle database, e.g. `ixmp-dev`, and confirm no exception is raised when adding disutility data to a Scenario stored on a JDBCBackend/Oracle database.
- Time: 20–30 minutes.
> Further work around iiasa/ixmp#425

- .github/pull_request_template.md
- doc/whatsnew.rst
> Release v2022.3.30

- .readthedocs.yml
- doc/whatsnew.rst
> Release v2022.7.25

- message_ix_models/util/node.py
> Improve typing of `nodes_ex_world()` for downstream mypy usage

- doc/whatsnew.rst
- message_ix_models/tests/tools/test_advance.py
- message_ix_models/tools/advance.py
Note that the CI checks all pass.
> Release v2022.8.17

- .github/workflows/lint.yaml
- .github/workflows/publish.yaml
- .github/workflows/pytest.yaml
- doc/whatsnew.rst
- message_ix_models/workflow.py
Also apply miscellaneous GHA workflow updates.
No review: routine release.
> Release v2022.11.7

- doc/whatsnew.rst
> Release v2023.2.8

- doc/whatsnew.rst
- message_ix_models/__init__.py
- message_ix_models/model/water/build.py
- message_ix_models/tests/util/test_cache.py
> Release v2023.4.2

- doc/whatsnew.rst
Note that the CI checks all pass.
> Release v2023.5.13

- doc/whatsnew.rst
> Release v2023.5.31

- doc/whatsnew.rst
> Release v2023.7.26

- doc/migrate.rst
- doc/whatsnew.rst
- message_ix_models/util/sdmx.py
- util/1-prep.sh
- util/2-migrate.sh
- util/reset.sh
- util/settings.sh
These describe/implement the process used for #88.
This PR can be updated as #88 (or #86, or another PR) is completed and merged.
Read the updated documentation.
> Add scripts, docs for migrating `message_data` code

- doc/whatsnew.rst
> Release v2023.9.2

- doc/whatsnew.rst
> Release v2023.9.12

- .github/workflows/pytest.yaml
"gh cache list" may occasionally give zero results; multiple results; or multiple results with the same cache key. Allow all of these to succeed with exit code 0.
Not required.
- ~Add, expand, or update documentation.~ N/A; CI changes only.
> Delete missing/multiple/duplicate caches in "pre-commit" job

- doc/whatsnew.rst
> Release v2023.11.24

- README.rst
- doc/conf.py
- doc/whatsnew.rst
> Release v2024.1.29

- .github/codecov.yml
- message_ix_models/tests/tools/iea/test_web.py
- message_ix_models/tools/iea/web.py
- message_ix_models/util/pooch.py
- pyproject.toml
Was added in #161 but is now on `main` and should be used there.
Needed by iiasa/message_data#549.
Note that the CI checks all pass.
> Update pooch URL for SSPUpdate data

- doc/whatsnew.rst
> Release v2024.4.22

- .github/workflows/pytest.yaml
This PR is identical to https://github.com/iiasa/ixmp/pull/527, see there for an extensive background description.
- ~[ ] Add, expand, or update documentation.~
- ~[ ] Update doc/whatsnew.~
> Use "macos-13" runner in "pytest" workflow

- doc/whatsnew.rst
> Release v2024.8.6

- .github/pull_request_template.md
- doc/api/tools.rst
- doc/index.rst
- doc/material/index.rst
- doc/project/circeular.rst
- doc/project/edits.rst
- doc/project/shape.rst
- doc/transport/index.rst
- doc/whatsnew.rst
- message_ix_models/cli.py
- message_ix_models/project/circeular/cli.py
Add stubs for upcoming project.
It's possible that multiple work-streams / PRs will start related to this project, so this provides a common set of landing-places for:
- Documentation.
- Code.
- CLI scripts and tools.
- Look at the preview build of the docs.
> Add CircEUlar

- message_ix_models/project/ssp/script/util/functions.py
- message_ix_models/tools/add_dac/__init__.py
**Update data reading in add_tech function**
use load_package_data in add_tech function to avoid hardcoding data paths for dac and ccs setup
**Required:** describe specific things that reviewer(s) must do, in order to ensure that the PR achieves its goal.
If no review is required, write “No review:” and describe why.
> update data reading in add_tech function

- doc/whatsnew.rst
- message_ix_models/data/material/aluminum/aluminum_trade.csv
- message_ix_models/model/material/data_aluminum.py
- message_ix_models/model/material/data_ammonia_new.py
- message_ix_models/model/material/data_power_sector.py
- message_ix_models/model/material/data_util.py
- message_ix_models/model/material/material_demand/material_demand_calc.py
- message_ix_models/model/material/util.py
This file was stored as a Git LFS pointer, i.e. the content on the branch was:
```
version https://git-lfs.github.com/spec/v1
oid sha256:b20a9561e4c08e451bf381c2733af88fa3ea0a9f776df9689b026f5434bb01d0
size 54793
```
However, the file was *not* listed in .gitattributes, at the top level or in any subdirectory. The result was that, in some cases, Git LFS would not know that it needed to 'smudge' this file —that is, fetch the LFS 'blob' and put it in the working directory.
This would in turn result in the checked-out file containing only the LFS pointer (`version https://` etc.), and code that used this file would fail. Most recently this happened in the scheduled nightly run of the "pytest" CI workflow, [here](https://github.com/iiasa/message-ix-models/actions/runs/12024191967/job/335229717 …
> Convert aluminum_trade.csv from Git LFS pointer

- .github/CODEOWNERS
- doc/api/workflow.rst
Per the suggestion by @volker-krey in today's learning session.
We should merge this by rebase, since it's a single commit.
Look at the diff.
> Add code owners for `.workflow`

- .github/workflows/pytest.yaml
- message_ix_models/model/material/build.py
- message_ix_models/model/material/data_petro.py
- message_ix_models/model/material/data_util.py
- message_ix_models/model/material/material_demand/material_demand_calc.py
- message_ix_models/model/transport/base.py
- message_ix_models/model/transport/operator.py
- message_ix_models/testing/__init__.py
- message_ix_models/tests/model/transport/test_config.py
- message_ix_models/tests/model/transport/test_operator.py
- message_ix_models/tests/report/test_compat.py
- message_ix_models/types.py
- message_ix_models/util/__init__.py
- message_ix_models/util/_dataclasses.py
- message_ix_models/util/cache.py
Closes #294. Supersedes #293.
- @glatterf42: Read the diff and note that the CI checks all pass.
- @macflo8 @r-aneeque: You may have got an automatic notification as code owners, but I've removed the request: There is no functional change to code, only to type hints in order to support this older version of Python.
- ~Add, expand, or update documentation.~ N/A; CI and type hint changes only
> Confirm support for minimum versions

- message_ix_models/data/ccs-dac/daccs_setup_data_leddev.yaml
- message_ix_models/data/ccs-dac/daccs_setup_data_ssp1dev.yaml
- message_ix_models/data/ccs-dac/daccs_setup_data_ssp2dev.yaml
- message_ix_models/data/ccs-dac/daccs_setup_data_ssp4dev.yaml
- message_ix_models/data/ccs-dac/daccs_setup_data_ssp5dev.yaml
- message_ix_models/project/ssp/script/util/functions.py
**Required:** This PR deactivates the growth constraints on the DAC activity to resolve the CCS issue observed in the ScenarioMIP Overshoot scenarios.
Since this is an experimental change, the parameters are just commented out, to enable an easy re-activation if needed later.
**Required:** no review required for merge to ssp-dev.
~~- [ ] Continuous integration checks all ✅~~
~~- [ ] Add or expand tests; coverage checks both ✅~~
~~- [ ] Add, expand, or update documentation.~~
~~- [ ] Update doc/whatsnew.~~
> Relax DAC growth constraints

- doc/project/geidco.rst
- doc/whatsnew.rst
Adding the documentation page for the project GEDICO (Pase IV). 
The HTML file has already been reviewed by the lead modeler of GEDICO IV (@guofei2016 ) through email, with @khaeru copied. 
The TBA part of the documentation will be updated as the GEDICO V project moves forward.
> Adding doc for project GEIDCO (Phase IV)

- .github/workflows/pytest.yaml
- doc/project/ssp.rst
- doc/whatsnew.rst
- message_ix_models/cli.py
- message_ix_models/model/transport/base.py
- message_ix_models/model/transport/build.py
- message_ix_models/model/transport/config.py
- message_ix_models/model/transport/structure.py
- message_ix_models/model/transport/workflow.py
- message_ix_models/project/ssp/cli.py
- message_ix_models/project/ssp/transport.py
- message_ix_models/testing/__init__.py
- message_ix_models/tests/project/ssp/test_transport.py
- message_ix_models/tests/tools/iea/test_web.py
- message_ix_models/util/context.py
- message_ix_models/util/genno.py
Closes #305.
The new method is labelled 'C' to distinguish from the previously-added methods.
The files in [this SharePoint folder](https://iiasahub.sharepoint.com/:f:/r/sites/eceprog/Shared%20Documents/SharedSocioEconomicPathways2023/Scenario_Vetting/v2.3_v2.4_Submission_Mar01_2025/Aviation%20emissions?csf=1&web=1&e=TTtz4g) (internal link) are generated from the ones in the neighbouring "Scenario_Reporting_Files" directory using this code and a crude script like:
```bash
#!/bin/sh
mix-models --platform=ixmp-dev ssp transport --method=C "SSP_LED_v2.3.1_baseline_1000f.xlsx"
mix-models --platform=ixmp-dev ssp transport --method=C "SSP_LED_v2.3.1_baseline.xlsx"
mix-models --platform=ixmp-dev ssp transport --method=C "SSP_LED_v2.3.1_SSP2 - Very Low Emissions.xlsx"
mix-models …
```
> Derive aviation final energy share from solved MESSAGEix-Transport scenarios

- pyproject.toml
Closes #327.
- ~Add, expand, or update documentation.~ N/A, packaging changes only
- ~Update doc/whatsnew.~ N/A, no notable user implications for this bump.
> Bump minimum sdmx1 v2.13.1 → v2.22.0

- doc/whatsnew.rst
- message_ix_models/model/transport/operator.py
- message_ix_models/project/ssp/transport.py
- message_ix_models/report/operator.py
- message_ix_models/tests/project/ssp/test_transport.py
> Two adjustments to `.project.ssp.transport`

- doc/index.rst
- doc/project/scenariomip.rst
- doc/project/ssp.rst
- doc/whatsnew.rst
- message_ix_models/data/ue-shares/trp_gas0.05.xlsx
- message_ix_models/data/ue-shares/trp_gas0.05_elec0.9.xlsx
- message_ix_models/project/ssp/script/scenarios/low.py
- message_ix_models/project/ssp/script/scenarios/very_low.py
- message_ix_models/project/ssp/script/util/functions.py
- message_ix_models/project/ssp/script/util/shares.py
- pyproject.toml
This PR cherry-picks some initial commits from the #235 branch.
There are also a few, minimal clean-up commits:
1. To address failures in the "Code quality" CI job:
- Ruff errors.
- Mypy errors —none in these commits, as it happens.
- Exclude (via pyproject.toml) added code without tests from coverage stats.
2. To add minimal docstrings.
- To minimize conflicts, these are at the top of the added files.
- They include reST `.. todo::` directives with lists of things to that should be done to improve code quality up to standard.
- Read the diff.
- Note that CI checks all pass.
> Merge part of `ssp-dev`

- message_ix_models/data/inter_pipe/config.yaml
- message_ix_models/project/geidco/report.py
- message_ix_models/project/geidco/run_baseline.py
- message_ix_models/tools/inter_pipe/generate_inter_pipe.py
**Required:** merging GEIDCO baseline development from forked remote to upstream remote. 
**Required:**No review
> Merging GEIDCO baseline development from forked remote to upstream remote

- .github/workflows/pytest.yaml
Workaround for #366.
Note the CI checks all pass.
- ~Add, expand, or update documentation.~ CI changes only.
> Limit ixmp4 < 0.11 in "pytest" CI workflow

- doc/whatsnew.rst
> Release v2025.7.23

- doc/whatsnew.rst
> Release v2025.8.7

- message_ix_models/tests/model/test_disutility.py
Closes #397.
- ~Add, expand, or update documentation.~ N/A; test suite changes only.
- ~Update doc/whatsnew.~ ditto
> Adjust test_disutility for message_ix#451
