iiasa/message-ix-models

.gitignore
doc/whatsnew.rst
message_ix_models/data/node/R11.yaml
message_ix_models/data/node/R14.yaml
message_ix_models/data/node/R32.yaml
message_ix_models/data/node/RCP.yaml

This PR updates .yaml files in /node, to include explanations on different outdated ISO 3166 country codes, which are still present in these regional aggregations.
For more info, see commits in iiasa/message_data#179 .

Update node files

---

.github/workflows/pytest.yaml
doc/api/disutility.rst
doc/api/model-build.rst
doc/api/util.rst
doc/index.rst
doc/whatsnew.rst
message_ix_models/model/disutility.py
message_ix_models/testing.py
message_ix_models/tests/model/test_disutility.py
message_ix_models/tests/test_testing.py
message_ix_models/tests/test_util.py
message_ix_models/util/__init__.py
message_ix_models/util/scenarioinfo.py

As well:
- 8 methods in `.util` used by `.model.disutility`.
- Install GAMS using iiasa/actions workflows, parallel to iiasa/ixmp#410 and iiasa/message_ix#452.
- Small tweaks and improvements to utilities, e.g. ScenarioInfo also stores `duration_period` when constructed off an existing scenario.
Partially addresses #4.

Migrate .model.disutility

---

message_ix_models/data/node/R12.yaml

The difference between the standard R11 and this new R12 is about separating the CPA region in the R11 model into two new regions for the R12 model, namely CHN (China) and CPA (the rest CPA).

adding R12 node yaml file

---

.github/workflows/pytest.yaml
README.rst
doc/api/util.rst
doc/conf.py
doc/develop.rst
doc/index.rst

- The docs for this repository are now at **https://docs.messageix.org/models**, not /models2
- Use a token on RTD/GitHub Actions to retrieve the Intersphinx inventory for the (private) message_data docs.
- Note that GitHub Actions (in the “Test documentation build using Spinx” step) can retrieve the Intersphinx inventory for message_data.
- Note that RTD can retrieve the Intersphinx inventory for message_data.
- ~Update doc/whatsnew.~ N/A, no functional changes

Update documentation URLs

---

.github/workflows/lint.yaml
doc/api/model.rst
doc/whatsnew.rst
message_ix_models/model/bare.py
message_ix_models/model/cli.py
message_ix_models/model/structure.py
message_ix_models/tests/model/test_cli.py
message_ix_models/tests/model/test_structure.py
message_ix_models/util/click.py

- Extend the set of options that can be added to click CLI commands via `@common_params()`.
- New utility function `message_ix_models.model.structure.codelists()` to return a list of all valid IDs for node/year codelists.

Add --years, --nodes CLI parameters

---

.github/workflows/lint.yaml
.github/workflows/publish.yaml
.github/workflows/pytest.yaml
doc/data.rst
doc/whatsnew.rst
message_ix_models/model/build.py
message_ix_models/tests/util/test_scenarioinfo.py
message_ix_models/util/__init__.py
message_ix_models/util/common.py
message_ix_models/util/context.py

Adds support for a setting “message local data” in the ixmp configuration file. This location can be used to read/write data (e.g. reporting output) in a system-local location by message-ix-models or downstream code.
This also addresses CI failures like [this one](https://github.com/iiasa/message-ix-models/runs/5314379290) caused by dependence on unadvertised ixmp behaviour that was cleaned-up in iiasa/ixmp#435.
Also:
- Squash a warning with pandas ≥1.4 in `merge_data()`.
- Update CI workflows.
- Close #45.
- Look at the changes to doc/data and doc/whatsnew.
- Note that the CI checks all pass.
Estimated time: < 5 minutes

Add “message local data” config key

---

setup.cfg

This PR adds `pyam-iamc >= 0.6` to the requirements. The aim to install minimum this version, is to possible remove the same requirement in _message_data_, which will then be implied by the requirement _message-ix-models_. 
Closes #36. 
<!--

Add requirement pyam-iamc

---

doc/api/util.rst
doc/pkg-data/node.rst
doc/whatsnew.rst
message_ix_models/tests/util/test_node.py
message_ix_models/util/__init__.py
message_ix_models/util/common.py
message_ix_models/util/node.py

By analogy to `adapt_R11_R14()` that was added in #24. This PR also generalizes the code that performs this adaptation into a `MappingAdapter` class that can be reused; so the definition of the function is reduced to:
https://github.com/iiasa/message-ix-models/blob/66f7e816dd268974e07de1d6c0bf154b486c410b/message_ix_models/util/node.py#L58-L62
Skim the diff; note that the CI checks all pass.

Add utility to adapt data from R11 to R12

---

setup.cfg

This PR aims to fix the failing lint workflow (e.g. [here](https://github.com/iiasa/message-ix-models/runs/6286453794?check_suite_focus=true#step:10:120)) in PR https://github.com/iiasa/message-ix-models/pull/62 and https://github.com/iiasa/message-ix-models/pull/68.

Add pyam to mypy's ignore_missing_imports

---

doc/api/testing.rst
doc/whatsnew.rst
message_ix_models/model/build.py
message_ix_models/testing.py
message_ix_models/tests/test_testing.py
message_ix_models/tests/test_util.py

This makes slight improvements to the `session_context` test fixture, and adds a test marker to skip/xfail tests on CI. These migrate changes originally made downstream in message_data for testing MESSAGEix-Transport.
Read the diff, note CI checks all pass.

Improve session_context, add .testing.not_ci

---

.github/workflows/pytest.yaml
doc/whatsnew.rst
pyproject.toml
setup.cfg

Test against multiple versions of `ixmp` and `message_ix`. This allows us to confirm which minimum versions are required for `message-ix-models` and in turn `message_data`, as well as notice potentially breaking changes in the lower levels of the stack.
Other changes:
- Bump versions for third party actions.
- Move some tool config from setup.cfg → pyproject.toml.

Run CI against multiple versions of `ixmp` and `message_ix`

---

.github/workflows/lint.yaml
doc/whatsnew.rst
message_ix_models/testing.py
message_ix_models/tests/test_cli.py
message_ix_models/tests/test_util.py
pyproject.toml

With [the release of pandas 1.5.0](https://pandas.pydata.org/docs/whatsnew/v1.5.0.html), we observed:
- `message_ix_models/tests/test_cli.py::test_cli_export_test_data` fails, e.g. [here](https://github.com/iiasa/message-ix-models/actions/runs/3087663077/jobs/4994576130#step:13:152).
- Multiple FutureWarnings.
This PR fixes both.

Adjust for pandas 1.5.0

---

doc/api/util.rst
doc/pkg-data/node.rst
doc/whatsnew.rst
message_ix_models/data/node/ZMB.yaml
message_ix_models/tests/model/test_structure.py
message_ix_models/util/__init__.py

This PR makes to small additions:
- Adding a Zambia yaml file, needed to run the national model for different users in the LEAP-RE project
- Adding a new utility function `same_time` which does copy the sets `time` into either `time_origin` or `time_dest`. This function is the analogous of `same_node`
There is not much to review or test. But please let me know if you notice something missing or needed

Add Zambia yaml file and function same_time, analogous of same_node

---

.github/workflows/lint.yaml
message_ix_models/tests/test_util.py

Changed in pint 0.21: [atol in numpy.isclose() now requires units](https://github.com/hgrecco/pint/issues/1658) to be specified, see e.g. [their commit](https://github.com/jules-ch/pint/commit/babed18e04b140b49c9a2eb9c84e71d954c2a5f7) that resolved their tests issues introduced by this change.
hgrecco/pint/issues/1277 might also occur somewhere in our code as workarounds that we can now possibly remove. 
Adding a unit to `atol` in `tests/test_util.py`'s `test_convert_units()`. Do we use `numpy.isclose()` or `numpy.allclose()` with units anywhere else? Does the new behaviour need documentation for our users?

Add units to atol in np.isclose

---

message_ix_models/model/structure.py

This prevents a "TypeError: … Code has no len()" that appears to occur only on pandas 2.0.0, and causes trouble in message_data. cf. iiasa/message_data#442

Ensure str indexers from generate_product()

---

doc/whatsnew.rst
message_ix_models/model/disutility.py
message_ix_models/model/structure.py

As of `sdmx1` v2.10, objects in the Information Model no longer have `.copy()` methods; the [release notes](https://sdmx1.readthedocs.io/en/latest/whatsnew.html#v2-10-0-2023-05-20) recommend using `copy.copy()` from the standard library instead.
This PR makes that change.

Adjust for sdmx1 v2.10.0

---

.github/codecov.yml
doc/api/disutility.rst
doc/api/model-snapshot.rst
doc/api/model.rst
doc/api/tools.rst
doc/index.rst
doc/whatsnew.rst
message_ix_models/data/test/macro/kgdp.csv
message_ix_models/model/config.py
message_ix_models/model/macro.py
message_ix_models/tests/model/test_macro.py
message_ix_models/workflow.py

- Add `message_ix_models.model.macro`, with utility functions `.generate()` and `.load()` for preparing MACRO calibration data.
- Workflow class:
- `Workflow.add_step()` now returns the name of the added step, rather than the WorkflowStep object. Experience showed the former was more often used in downstream code.
- New method `Workflow.guess_target()` to look up the most-recent scenario_info or platform_info.
- Read the diff and modified docs.
- Note the CI checks all pass.

Miscellaneous enhancements for 2023-W24

---

message_ix_models/tests/util/test_context.py

Closes #112 by marking the test as flaky. Through discussion with @khaeru, we agreed that this is the best option for now; should the test make more issues in the future, we can still identify its root cause.
Note that the second commit here is temporary until iiasa/ixmp#490 is merged. The additional dependency here can then be dropped again.

Handling flaky tests

---

.github/workflows/lint.yaml
doc/api/report/default-config.rst
doc/api/report/index.rst
doc/index.rst
doc/whatsnew.rst
message_ix_models/cli.py
message_ix_models/report/__init__.py
message_ix_models/report/cli.py
message_ix_models/report/computations.py
message_ix_models/report/sim.py
message_ix_models/report/util.py
message_ix_models/testing.py
message_ix_models/tests/report/test_computations.py
message_ix_models/tests/test_report.py
message_ix_models/tests/util/test_logging.py
message_ix_models/util/_logging.py
message_ix_models/workflow.py
pyproject.toml

This branch makes additional adjustments to the branch for #116 after the automated migration process.
- Read the migrated docs and ensure they are coherent.
- [Preview build](https://docs.messageix.org/projects/models/en/migrate-report-adjust/api/report/index.html)

Manual adjustments for `migrate-report`

---

message_ix_models/data/report/global.yaml
message_ix_models/report/__init__.py

- Only add "y::model", "y0" if not already defined. After iiasa/message_ix#738 (that is, first message_ix release after 3.7.0), these will be defined in the Reporter by default.
- Add a new "defaults" callback to hold settings and computations always used.
- ~Update doc/whatsnew.~ Covered by #116.

Adjust for iiasa/message_ix#738

---

.github/workflows/pytest.yaml

The change introduced in #124 contained a bash syntax error; this fixes.
- ~Add, expand, or update documentation.~ N/A; CI changes only

Fix bash syntax in "Code quality" CI job

---

.github/workflows/pytest.yaml
.gitignore
doc/Makefile
doc/api/report/index.rst
doc/api/testing.rst
doc/repro.rst
doc/whatsnew.rst
message_ix_models/data/technology.yaml
message_ix_models/model/config.py
message_ix_models/report/__init__.py
message_ix_models/report/compat.py
message_ix_models/report/computations.py
message_ix_models/report/sim.py
message_ix_models/tests/report/test_compat.py
message_ix_models/tests/report/test_computations.py
message_ix_models/tests/test_report.py
message_ix_models/util/scenarioinfo.py
pyproject.toml

This PR adds code that mirrors the behaviour of `message_data` (‘legacy’) reporting, as an exploration of how to exactly replicate these calculations using `genno`. For this purpose, the code only replaces the portions of `message_data.tools.post_processing.default_tables.retr_CO2emi` that calculate CO₂ emissions from transportation.
The goals are:
- The magnitudes and labels on the data are the same (to within a small tolerance) as those produced by `message_data`. (However, per [this Slack thread](https://iiasa-ece.slack.com/archives/CD0GBHHA4/p1698062587533069), there does not exist a legacy reporting output for the snapshot, and it would be difficult to produce one due to changes to the units.)
- The code is legible, and it is clear how the genno-based code mirrors the logic of the …

Report CO₂ emissions from transportation

---

doc/api/model-snapshot.rst

The domain (doi.org) was missing, making this a broken link.
Look at the RTD auto build and ensure the link is no longer broken.
- ~Update doc/whatsnew.~ N/A

Correct DOI URL in doc/api/model-snapshot

---

.pre-commit-config.yaml
message_ix_models/report/plot.py
message_ix_models/testing/__init__.py
message_ix_models/tests/util/test_click.py
message_ix_models/util/click.py

As raised by @adrivinca. This was previously-untested behaviour that the "water-ix" CLI command relied on; changes in #137 caused it to no longer work.
The PR restores the original behaviour by refining the code passed to `exec_cb()`, and adds a test to confirm.
- Read message_ix_models/util/click.py in the diff.
- Note the CI checks all pass, especially the newly-added `.tests.util.test_click.test_regions()`.

Ensure --regions CLI option can be used twice

---

.pre-commit-config.yaml
doc/api/tools.rst
doc/conf.py
doc/whatsnew.rst
message_ix_models/model/structure.py
message_ix_models/tests/tools/test_wb.py
message_ix_models/tools/wb.py

This PR adds code to:
1. Retrieve the World Bank (WB) World Development Indicators (WDI) country categorization to income groups, as described at https://datahelpdesk.worldbank.org/knowledgebase/articles/906519; then use these to annotate the CL_REF_AREA_WDI code list.
2. Use the result of (1) to determine income group categorization for arbitrary MESSAGE node lists—that is, the R12 list and others—by counting membership or population of the countries in each region.
3. As part of (2), replace, combine, or relabel groups.
This provides a transparent and repeatable way of determining this categorization by reference to established sources. It will be useful in applying assumptions in, for instance, the transport realizations of the 2024 SSPs, since these can be distinguished by income …

Derive income categories for MESSAGE node lists

---

message_ix_models/util/scenarioinfo.py

As discovered by @behnam-zakeri, our current code should either require python >= 3.10, or remove the `dataclass()` argument `kw_only` until this is the case.
Should we leave a note somewhere that we strongly encourage users to still use the syntax you were trying to enforce, @khaeru?
Please note: this PR leaves a TODO comment to come back to it. The other changes are small notes that mypy complained about. 
- ~[ ] Add, expand, or update documentation.~

Remove Python 3.10-exclusive kw_only dataclass argument temporarily

---

message_ix_models/data/test/MESSAGEix-GLOBIOM_1.1_R11_no-policy_baseline/DEMAND.csv.gz
message_ix_models/util/context.py

As suggested by @khaeru in #147, this PR removes `message_ix_models/data/test/MESSAGEix-GLOBIOM_1.1_R11_no-policy_baseline/DEMAND.csv.gz` since it's not mentioned anywhere in the current code base.
Trying to run the tests locally, I got stuck on `test_snapshot`, which might be most crucial here. `test_cli` also complained that `ixmp.utils` has no attribute `parse_url`, so I updated this to `ixmp.util`.
- Do you think we need to leave a note for when we are adding code/data again that need to reference both `demand` and `DEMAND`?
- ~[ ] Add or expand tests; coverage checks both ✅~ All tests still working
- ~[ ] Add, expand, or update documentation.~ Do we mention this file somewhere? A [quick …

Delete unused DEMAND data file

---

doc/whatsnew.rst
message_ix_models/testing/__init__.py
message_ix_models/tests/util/test_scenarioinfo.py
message_ix_models/util/scenarioinfo.py

Currently, if either the commodity or technology lacks units, the exception is internal to pint and could be hard to interpret:
```
File "/home/khaeru/vc/iiasa/models/message_ix_models/util/scenarioinfo.py", line 265, in io_units                                                                                                                                  
return self.units_for("commodity", commodity) / self.units_for(                                                                                                                                                                  
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
```

Raise informative exception from ScenarioInfo.io_units()

---

doc/pkg-data/codelists.rst
doc/whatsnew.rst
message_ix_models/data/commodity.yaml

This is needed for MESSAGEix-Transport (see message_data#535) to understand which IEA EWEB flows are aggregated to the MESSAGEix-GLOBIOM "transport" commodity.

Annotate "transport" commodity with iea-eweb-flow

---

message_ix_models/tools/wb.py

sdmx1 v2.14.0 was released [2024-02-20](https://sdmx1.readthedocs.io/en/latest/whatsnew.html#v2-14-0-2024-02-20) with improved but stricter handling of query parameters.
This prompted failures like [this](https://github.com/iiasa/message-ix-models/actions/runs/7984254881/job/21800794183#step:9:777) in the "pytest" CI workflow, because `.wb.assign_income_groups()` used a parameter name "startperiod" that was neither snake_case ("start_period") nor lowerCamelCase ("startPeriod").
The PR corrects.
- ~Add, expand, or update documentation.~ N/A, bugfix only

Adjust .wb.assign_income_groups() for sdmx 2.14.0

---

.github/workflows/pytest.yaml

Pytest renamed the hook argument `startdir` to `start_path` in v8.1.0, see https://github.com/iiasa/ixmp/pull/519 for more information. While this has been fixed on the latest version of ixmp upstream, our CI test suite doesn't always install that version. This PR adds a step that installs a pinned pytest version (v8.0.0) if necessary.
- ~[ ] Add or expand tests; coverage checks both ✅~ Just a CI change
- ~[ ] Add, expand, or update documentation.~ Just a CI change
- ~[ ] Update doc/whatsnew.~ Just a CI change

Pin pytest version to fix CI

---

doc/whatsnew.rst

Needed by nightly and MESSAGEix-Transport jobs on message_data `dev` branch; see [here](https://github.com/iiasa/message_data/actions?query=branch%3Adev).

Release v2024.4.2

---

message_ix_models/tests/tools/iea/test_web.py

We can currently observe [an incompatibility of dask with python 3.11.9](https://github.com/dask/dask/issues/11038) e.g. in the message-ix-models CI. This is fixed in version 2024.4.1 of dask, but our CI runs `pip install .[docs,tests] "dask < 2024.3.0" "genno < 1.25" "pandas < 2.0" "pytest == 8.0.0"` for message-ix-models with message_ix 3.6.0 and below.
We expect that removing the pin for the dask version entails solving a dependency mess since we would need to adhere to requiring dask-expr. So for now, we opt to XFail the test depending on dask instead.
@khaeru, should I mention this PR in a comment in-line? I'm not sure what else to reference there.
- ~[ ] Add, expand, or update documentation.~ Just test suite changes.
- ~[ ] …

Mark incompatible dask-python-combination-tests as XFail

---

.github/workflows/pytest.yaml

Closes #173 by removing the workaround. Pyam released v2.2.2 recently, which should include the fix we were waiting for.
- ~[ ] Add or expand tests; coverage checks both ✅~ Only internal clean up.
- ~[ ] Add, expand, or update documentation.~ Only internal clean up.
- ~[ ] Update doc/whatsnew.~ Only internal clean up.

Remove workaround for #173

---

doc/api/model-snapshot.rst
doc/cli.rst
doc/conf.py
doc/index.rst
doc/install.rst
doc/quickstart.rst
doc/whatsnew.rst

This PR supersedes https://github.com/iiasa/message_data/pull/312 and thus fixes https://github.com/iiasa/message_data/issues/287 once we merge it. The main reason for migrating this PR is that we now have a snapshot of a global baseline model available at Zenodo, so there might be demand for having these instructions be public, too.
Thanks a lot to @jkikstra for writing up the original issue and to @LauWien for starting the original PR. 
After going through the original material, I think almost everything should be included in the new docs except for some Common Issue that @jkikstra reported:
> - a GAMS error the first time you are doing `scenario.solve()`:
```
com.gams.api.GAMSException: com.gams.api.GAMSException: GAMS system directory is both not specified and not found from your …
```

Create "Quick starting guide to running MESSAGEix-GLOBIOM" for occasional users

---

pyproject.toml

I checked the results of `python -m build` after merging #159 and found that both the .tar.gz and .whl outputs were about 10 MB. This was because the entire /doc/ directory—including many images added by that other PR—was included in both files.
This PR adjusts our setuptools config so that the /doc/ directory is:
- included in the .tar.gz source distribution,
- excluded from the .whl distribution.
This follows the practice of [`coverage`](https://pypi.org/project/coverage/#files) and several other packages I looked at. It also ensures that users who install from .whl (with pip) don't wind up with an extra directory named `site-packages/doc/` that contains the message-ix-models docs. (AFAIK, distributing these 'dangling' directories outside the ones strictly related to the package is bad …

Adjust packaging

---

doc/whatsnew.rst
message_ix_models/data/iea/WEO_2023_PG_Assumptions_STEPSandNZE_Scenario.xlsx
message_ix_models/tests/tools/costs/test_regional_differentiation.py
message_ix_models/tools/costs/projections.py
message_ix_models/tools/costs/regional_differentiation.py

Update costs module to move from using the 2022 WEO release to using the 2023 WEO data release
Main changes made:
- Upload 2023 data file
- Modify code to read in 2023 data release
- Use 2022 USD to 2001 USD conversion (instead of 2021 USD to 2001 USD)
- Use the new latest historical values (2022) for the regional differentation
Additionally, I've changed a few lines in the code to address the comments that were left on #186 which were not properly fixed in that PR.
For @khaeru and/or @glatterf42 : Read the diff and note that the CI checks all pass.

Use 2023 WEO data in `tools.costs`

---

doc/whatsnew.rst
message_ix_models/tools/costs/config.py
message_ix_models/tools/costs/projections.py

Update costs module to include 2110 in output by default
Currently the default `final_year` in `tools.costs` is 2100, which does not pair well with MESSAGEix's final year usally being 2110. Currently, users can change the `final_year` themselves as a parameter when creating their `Config` file, but given the use-base of this tool is mostly our internal team, I'm changing the default `final_year` to 2110.
Note that this does not mean costs are projected to 2110 now -- costs are still only projected to 2100. The module copies over 2100 projected costs for all years after 2100.
~~Also note that this PR is currently pointing to #187 -- I was thinking it would be best to wait for that PR to be merged first, then point this PR to main. But happy to revise as necessary.~~
Branch now has been …

Change the default final year in `tools.costs` to 2110

---

doc/index.rst

This was missed in #189, and as a result one can't see the new module in the "Model variants" section of the left navbar or the ToC on the index page.
Look at the RTD docs build for this PR and confirm that .model.material appears in both places: https://iiasa-energy-program-message-ix--196.com.readthedocs.build/projects/models/en/196/
- ~Update doc/whatsnew.~ Silent clean-up of PR that's already mentioned.

Add doc/material/index to doc/index

---

.github/workflows/pytest.yaml
message_ix_models/tests/test_workflow.py

This PR updates the "pytest" CI workflow to address three causes of failures:
- With NumPy 2.0.0 we run into unionai-oss/pandera#1685, which is a dependency via various reporting code → `pyam-iamc` → `ixmp4`. We apply the mitigation discussed at khaeru/genno#140. This is parallel to iiasa/message_ix#854.
- hgrecco/pint#2007; see iiasa/ixmp#534.
- ts-graphviz/setup-graphviz#630. This mirrors changes made in iiasa/ixmp#535 and iiasa/message_ix#854.
These are temporary work-arounds, are marked accordingly, and should be removed when the respective upstream packages are fixed.
- ~Update release notes.~

Adjust CI for numpy 2.0, graphviz, pint

---

doc/whatsnew.rst
message_ix_models/model/build.py
message_ix_models/tests/model/test_build.py
message_ix_models/util/__init__.py

In #159 we adjusted `.model.build.apply_spec()` to add any new `node` set elements also to the ixmp.Platform `region` codelist.
I noticed this generates a lot of "log spam", such as [here](https://github.com/iiasa/message_data/actions/runs/9738457433/job/26872089471#step:17:8678):
```
____________________________ test_add_missing_years ____________________________
[gw7] linux -- Python 3.12.2 /home/runner/actions-runner/_work/_tool/Python/3.12.2/x64/bin/python
----------------------------- Captured stdout call -----------------------------
message_ix_models.testing.bare_res: Create 'MESSAGEix-GLOBIOM R11 YB/baseline' for testing
—.testing.bare_res  Create 'MESSAGEix-GLOBIOM R11 YB/baseline' for testing
message_ix_models.model.bare.create_res: Create …
```

Adjust apply_spec() to reduce log verbosity

---

.github/workflows/pytest-snapshots.yaml
.github/workflows/pytest.yaml

https://github.com/iiasa/ixmp/pull/532 deleted some libraries that were used to run GAMS, which should now be read directly from a GAMS subdirectory. This PR adjusts the version of GAMS used in CI to check if this newer version enables finding the libraries.
- ~[ ] Add or expand tests; coverage checks both ✅~ Just internal CI.
- ~[ ] Add, expand, or update documentation.~ Just internal CI.
- ~[ ] Update doc/whatsnew.~ Just internal CI.

Bump GAMS version in CI workflows to adjust for ixmp changes

---

doc/api/tools-costs.rst
doc/whatsnew.rst
message_ix_models/tools/costs/config.py
message_ix_models/tools/costs/demo.py
message_ix_models/tools/costs/projections.py

Add option in costs model (`use_vintages`) which affect how fixed O&M costs are projected
Currently, fixed O&M costs (`fix_cost`) are projected in this way: for a certain `year_vtg`, the `fix_cost` is a percentage of investment cost (`inv_cost`). Then from the `year_vtg` to the end of the modeling horizon, the fixed O&M cost changes by a rate specified by `fom_rate` (as of present, the default `fom_rate` is 0, so there is no change).
However, this does not match with the current implementation in MESSAGEix. To match the MESSAGEix implementation, the `fix_cost` in a certain `year_act` should be the same across all `year_vtg`. As such, I've added an option to specify `use_vintage`. If `True` then the first projection method for `fix_cost` is used. If `False` (which is the default setting …

Create option in `tools.costs` to keep fixed O&M costs same across vintages

---

doc/whatsnew.rst
message_ix_models/tools/costs/gdp.py
message_ix_models/tools/wb.py

Small fix to `total_gdp` and `total_population` columns being switched in `message_ix_models.tools.costs.gdp.process_raw_ssp_data()`
In the `message_ix_models.tools.costs.gdp.process_raw_ssp_data()` function that pulls and combines SSP data in `tools.costs`, there is a block of code that converts the data in the `Computer()` into a `pandas` DataFrame, with each computer key being a column. However, the naming of the columns are switched (`total_population` and `total_gdp`). So, I just swapped them.
From what I can tell, this has zero impact on the actual costs calculations, as these DataFrames columns are not used anywhere (and are later even dropped). The calculation of GDP per capita happens before this DataFrame is created, here: …

Fix naming of GDP and population columns in SSP data aggregation within `tools.costs`

---

doc/repro.rst
doc/whatsnew.rst

- Merge/consolidate text formerly in doc/repro.rst in message_data.
- Update and improve text to match current practice.
- Organize page under the headings "Documentation", "Testing", "Versioning and naming"
- Add a list and scheme for external model names (closes #224)
- View the diff.
- Read the RTD preview of the updated page: https://iiasa-energy-program-message-ix--226.com.readthedocs.build/projects/models/en/226/repro.html and note:
- Spelling and grammar errors.
- Changes for clarity.
- Is the text useful as a guide for practice in IIASA ECE?
- Is the text useful to explain to external audiences the meaning of model names?
- Leave comments and suggestions per the above.

Expand ‘Reproducibility’ docs page

---

message_ix_models/report/legacy/pp_utils.py

The snapshot tests have been failing for a while now. Initially, if I remember correctly, there was some issue with retrieving the snapshots consistently, but that seems to be resolved. Now, one test fails because it's looking for the `PRICE_EMISSION_NEW` variable: the legacy reporting we migrated is built on top of https://github.com/iiasa/message_ix/tree/issue/723, which introduced that variable name to fix `PRICE_EMISSION`. 
While we have unfortunately still not finished the corresponding PR, the branch has progressed to a point where `PRICE_EMISSION` was actually updated instead of a new helper variable introduced. This PR thus adjusts the variable name the migrated legacy reporting expects.
- Note that the `TEMPORARY` commit …

Fix snapshot tests

---

doc/whatsnew.rst
message_ix_models/util/click.py

The `mix-models --ssp=` CLI option is used in the SSP 2024/ScenarioMIP workflows, but originally had only SSP1 through SSP3 as accepted values. This adds SSP4, SSP5, and LED.

Extend SSP argument options

---

doc/whatsnew.rst
message_ix_models/tools/costs/decay.py

Small fix to the cost decay in `tools.costs` to reach the reduction rate specified by 2100
Currently, the decay is applied so that the cost reduction rate is reached by `Config.final_year`, which is 2110 -- but this should really be 2100. So if the cost reduction rate is 10%, that 10% reduction (relative to the base year) is reached in 2110, not 2100. Therefore the 2100 value is maybe around 9% less than the base year value (or something like that).
Further down the line, the tool also takes the 2100 value and repeats it until `Config.final_year` (since 2110 isn't really a model year), so essentially the cost projections never officially reach the cost reduction rate specified (it gets very close).
This branch is derived off of the `costs/reconfigure-modules` branch, so PR #221 should be …

Change decay to reach cost reduction specified by 2100 (instead of 2110) `tools.costs`

---

message_ix_models/data/ue-shares/trp_gas0.05.xlsx
message_ix_models/data/ue-shares/trp_gas0.05_elec0.9.xlsx
message_ix_models/project/ssp/script/scenarios/low.py
message_ix_models/project/ssp/script/scenarios/very_low.py
message_ix_models/project/ssp/script/util/functions.py
message_ix_models/project/ssp/script/util/shares.py

This PR adds my scripts that I developed during the ScenarioMIP submission, to modify the "Low" and "Very Low" scenarios.
This PR is associated with the following:
- The branch `ssp-dev`
- The PR: #235 
- The issue: #234 
The changes made to the "Low" (SSP1 & SSP2) scenarios were:
- Removed `growth_activity_lo` and `initial_activity_lo` for `bof_steel`
- Changed `growth_activity_up` for `dri_gas_steel`, `dri_h2_steel`, `eaf_steel` from 0.02 to 0.075
- Changed` initial_activity_up` for `dri_gas_steel`  and `dri_h2_steel` from 0.1 to 1
- Added balance equalities
The changes made to the "Very Low" (SSP1 & LED) scenarios were:
- The same changes made to the "Low" scenarios above
- Disallow the revival of `loil_rc` and `biomass_rc` in residential & commercial sector by changing the …

Add scripts to modify "Low" and "Very Low" ScenarioMIP/SSP scenarios

---

.github/workflows/pytest.yaml
message_ix_models/model/water/data/demands.py

This is a twin of https://github.com/iiasa/message_ix/pull/887, fixing the CI test suite by pinning dask until genno is compatible with the latest versions of it.
- ~[ ] Add, expand, or update documentation.~ Just CI.
- ~[ ] Update doc/whatsnew.~ Just CI.

Replace resolved numpy workaround with dask workaround

---

message_ix_models/data/material/steel/Global_steel_MESSAGE.xlsx

Update steel diffusion constraints as follows: 
- removed growth_activity_lo and initial_activity_lo for bof_steel from 2030 onwards
- changed the growth_activity_up for dri_gas_steel, dri_h2_steel, and eaf_steel to 0.075 from 2030 onwards
- changed the initial_activity_up for dri_gas_steel and dri_h2_steel to 1.0 from 2030 onwards
No review is needed, just changing the parameters in Excel data file as agreed before.

Update steel diffusion constraints

---

doc/whatsnew.rst
message_ix_models/data/costs/cooling/tech_map.csv
message_ix_models/model/water/cli.py
message_ix_models/model/water/data/water_for_ppl.py
message_ix_models/tests/model/water/data/test_water_for_ppl.py
message_ix_models/tests/util/test_click.py
message_ix_models/util/click.py

This PR changes the code in the `water` model to use the regionally-differentiated and scenario-specific cost projections created by `tools.costs`.
Currently the costs for cooling technologies are being read from an input CSV and kept constant over the time horizon. 
This PR's branch is derived from the `wat_SSP_upd2` branch, so this branch can be rebased once #242 is closed or merged into that branch.
For @adrivinca: Check if the implementation is correct and if the outputs make sense.
For @khaeru and/or @glatterf42 : Read the diff and note that the CI checks all pass.
- ~[ ] Add or expand tests; coverage checks both ~ not needed, no new function added
- ~[ ] Add, expand, or update documentation. ~ not needed, no new function added

Update `water` to use cost projections from `tools.costs`

---

.github/workflows/pytest-snapshots.yaml

Our CI `Test snapshots` failed today, complaining that `The workflow is not valid. .github/workflows/pytest-snapshots.yaml (Line: 18, Col: 5): A mapping was not expected`.
Looking at [the docs](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#env), a mapping is allowed, but apparently not a nested mapping. Thus, this PR removes the `version` level in the `env` mapping (and temporarily enables `Test snapshots` to see if they run now).
- Read the diff and note that the CI checks all pass (in particular `Test snapshot`).
- ~[ ] Add, expand, or update documentation.~ Just CI.
- ~[ ] Update doc/whatsnew.~ Just CI.

Fix snapshot test environment variables

---

doc/whatsnew.rst
message_ix_models/data/costs/materials/cost_reduction.csv
message_ix_models/data/costs/materials/scenarios_reduction.csv
message_ix_models/tests/tools/costs/test_decay.py
message_ix_models/tools/costs/decay.py

This PR adds the functionality for a user to add specific cost reduction values and scenario assumptions in the costs tool.
This PR closes: 
- #251 
The logic is as follows (for both the cost reduction values and the reduction scenario categories):
1. If values/categories are specified in the non-energy module for a technology, then this value is used. If such values exist already in the energy module, the value in the non-energy module takes precedence (similar to how base year costs are implemented in this way) and replaces the energy module's values.
2. If no values/categories are specified in the non-energy module for a technology but that technology is mapped to an energy technology, then the mapped energy technology's values/categories are used.
3. If no values/categories are …

Add functionality in `tools.costs` to specify cost reduction scenarios and values

---

message_ix_models/data/ccs-dac/co2infrastructure_data_leddev.yaml
message_ix_models/data/ccs-dac/co2infrastructure_data_ssp1dev.yaml
message_ix_models/data/ccs-dac/co2infrastructure_data_ssp2dev.yaml
message_ix_models/data/ccs-dac/co2infrastructure_data_ssp3dev.yaml
message_ix_models/data/ccs-dac/co2infrastructure_data_ssp4dev.yaml
message_ix_models/data/ccs-dac/co2infrastructure_data_ssp5dev.yaml
message_ix_models/data/ccs-dac/daccs_setup_data_leddev.yaml
message_ix_models/data/ccs-dac/daccs_setup_data_ssp1dev.yaml
message_ix_models/data/ccs-dac/daccs_setup_data_ssp2dev.yaml
message_ix_models/data/ccs-dac/daccs_setup_data_ssp3dev.yaml
message_ix_models/data/ccs-dac/daccs_setup_data_ssp4dev.yaml
message_ix_models/data/ccs-dac/daccs_setup_data_ssp5dev.yaml
message_ix_models/project/ssp/script/util/functions.py

This PR has 2 updates:
1. Remove operation reserve potential for DAC. The values are for electricity storage-equipped DAC but this variant is removed in this implementation
2. Update injection rate for CO2 according to the recent tests and agreed values
3. Switch 'co2trans' and 'commodity' values for consistency. No changes on the resulting .gdx file are expected. CO2_cc plus co2 output values must equal to 1.
**Required:** describe specific things that reviewer(s) must do, in order to ensure that the PR achieves its goal.
If no review is required, write “No review:” and describe why.

CCS and DAC updates

---

.github/CODEOWNERS
doc/Makefile
doc/develop.rst
doc/whatsnew.rst

This PR adds an initial set of code owners, as discussed at today's MESSAGE team meeting.
Some notes:
- @measrainsey and @GamzeUnlu95 are added so we can soon try out the process of identifying (a) person(s) to take over these codes and making a follow-up PR that modifies the CODEOWNERS file.
- We could also add a line `.github/CODEOWNERS  @khaeru @glatterf42` or similar to ensure people are requested to review changes to the owners file itself. I would need to look around for other uses of this feature to see if that's common.
I've requested review from everyone who'll be affected by this change.
- Check whether the paths in the added file include all the files you see yourself as responsible for.
- None missing.
- None included which are actually owned by someone else.
- Approve.

Add initial code owners

---

.github/workflows/pytest-snapshots.yaml

#281 renamed the environment variable for the python version of our snapshot CI test from `python` to `python-version`. The uv action could not find `env.python` and thus saw no input for `python-version`, which it needs to create a venv. And without a venv, we get [the error we see in today's snapshot CI test](https://github.com/iiasa/message-ix-models/actions/runs/12922591067/job/36038523512).
This PR adjust the name of the environment variable used for the uv action.
- Read the diff and note that the variable name used now is correct.
- ~[ ] Add, expand, or update documentation.~ Just CI.
- ~[ ] Update doc/whatsnew.~ Just CI.

Fix envvar name in snapshot CI

---

.github/workflows/pytest.yaml
README.rst
doc/conf.py
doc/whatsnew.rst
message_ix_models/model/transport/config.py
message_ix_models/model/transport/ldv.py
message_ix_models/model/transport/testing.py
message_ix_models/project/ssp/cli.py
message_ix_models/report/__init__.py
message_ix_models/testing/__init__.py
message_ix_models/tests/model/transport/test_build.py
message_ix_models/tests/model/transport/test_data.py
message_ix_models/tests/model/transport/test_ikarus.py
message_ix_models/tests/model/transport/test_ldv.py
message_ix_models/tests/model/transport/test_report.py
message_ix_models/tests/project/ssp/test_transport.py
message_ix_models/tests/util/test_context.py
message_ix_models/types.py
message_ix_models/util/_dataclasses.py
message_ix_models/util/cache.py
message_ix_models/util/context.py
message_ix_models/util/scenarioinfo.py
pyproject.toml

#281 shifted the main event trigger for the "pytest" CI workflow from pull_request to pull_request_target. However, it erroneously omitted to explicitly specify the ref to be checked out. This is necessary because actions/checkout (and in this repo also francisbilham11/action-cached-lfs-checkout) will default to checking out $GITHUB_REF; for the pull_request_target event, this is the *base* branch commit, unlike for pull_request, where it is the source branch commit.
As a consequence of this, when merging #259, the "pytest" workflow appeared to pass, but this was in fact running the tests on `main`, while the tests did *not* all pass on the PR branch. Thus when #279 #282 were updated with rebase, they picked up these failing tests.
This PR:
- Corrects the pytest workflow, in a similar way …

Check out correct ref in "pytest" CI workflow

---

message_ix_models/model/material/data_util.py
message_ix_models/project/ssp/script/scenarios/ccs_dac.py
message_ix_models/project/ssp/script/scenarios/low_overshoot.py
message_ix_models/project/ssp/script/util/functions.py
message_ix_models/tools/costs/config.py

The `final_year` attribute has been replaced by `final_model_year`. Currently `final_year` is still kept in the Config, but it should really be removed. In this PR, I would be removing the `final_year` attribute.
~However, this would cause some parts of the codebase to break. Namely, when `gen_te_projections()` is used, as that function has a `tools.costs` `Config` class that uses the `final_year` parameter:~
1. https://github.com/iiasa/message-ix-models/blob/ea8477ab40dca36dc7ed5777fc1b2fa414adcfb7/message_ix_models/project/ssp/script/util/functions.py#L281-L288
2. https://github.com/iiasa/message-ix-models/blob/ea8477ab40dca36dc7ed5777fc1b2fa414adcfb7/message_ix_models/project/ssp/script/scenarios/ccs_dac.py#L185-L192
3. https://github.com/iiasa/message-ix-models/blob/ea8477ab40dca36dc7e …

Remove `final_year` attribute from Config

---

.github/workflows/pytest.yaml

Further correction to #288 as described at https://github.com/iiasa/message-ix-models/pull/291#issuecomment-2640100989.
Note [here](https://github.com/iiasa/message-ix-models/actions/runs/13182382902/job/36796814007#step:4:3) that the explicit 'ref:' input is given in the checkout step, using the value from the `needs.check` payload [here](https://github.com/iiasa/message-ix-models/actions/runs/13182382902/job/36796814007#step:3:17).
- ~Add, expand, or update documentation.~ N/A, CI changes only

Check out correct ref in "pytest" CI job

---

doc/api/util.rst
doc/conf.py
doc/distrib.rst
doc/howto/index.rst
doc/howto/migrate.rst
doc/howto/quickstart.rst
doc/howto/release.rst
doc/howto/unicc.rst
doc/index.rst
doc/repro.rst
doc/whatsnew.rst
message_ix_models/cli.py
message_ix_models/tests/test_cli.py
message_ix_models/tests/util/test_slurm.py
message_ix_models/util/slurm.py

This PR…
- Adds a `mix-models sbatch` CLI command that simplifies usage with SLURM, for instance on UnICC.
This closes #284.
- Collects some docs pages under a 'HOWTO' section, with instructions on HOWTO Write a HOWTO.
- Read the [added documentation](https://iiasa-energy-program-message-ix--291.com.readthedocs.build/projects/models/en/291/api/util.html#module-message_ix_models.util.slurm) via the preview build.
- Check out the branch on UnICC.
- Run a command like `mix-models sbatch -- config show`.

Add `.util.slurm` and CLI

---

.github/workflows/pytest.yaml
doc/whatsnew.rst

With ixmp/message-ix v3.10.0 both released, we add these to the "pytest" CI workflow matrix. This will help us ensure that message-ix-models continues to work with both these latest releases and the evolving `main` branches for those repos.
According to our [Upstream version policy](https://docs.messageix.org/projects/models/en/latest/develop.html#upstream-version-policy):
> [message-ix-models supports t]he most recent 4 minor versions [of ixmp/message-ix], or all minor versions released in the past two (2) years—whichever is greater.
- The most recent 4 minor versions = 3.7, 3.8, 3.9, 3.10.
- Versions released in the last 2 years = versions released on 2023-02-24 or later. [v3.7.0 is the oldest version released since that date (on …

Test against ixmp/message-ix v3.10.0

---

.github/workflows/pytest.yaml

The recent release v3.10.0 of message_ix and ixmp and #299 broke our CI by exposing that we don't properly handle version comparisons for extra comparisons at the moment. This PR fixes that.
In our `pytest` CI workflow, we add extra dependency requirement for specific versions. At the moment, this is done based on string comparison, but with `"v3.10.0"` coming into play, these begin to fail: 
```python
>>> "v3.10.0" < "v3.1.0"
False
>>> "v3.10.0" < "v3.7.0"
True
``` 
This results in incompatible dependencies being installed, causing the CI to fail.
@khaeru suggested to use [packaging.version](https://packaging.pypa.io/en/latest/version.html) instead of string comparisons, which I tried to add now. There's just one catch: these versions can't parse `"main"`. 
I thought about using an …

Fix CI for `message_ix` v3.10.0

---

.github/CODEOWNERS

As discussed and agreed at the 2025-02-20 MESSAGE team meeting, this PR updates the CODEOWNERS file to keep it current with the actual team and practice:
- Add @adrivinca @macflo8 @ywpratama as sole owners of input data files for particular cost 'modules'.
- Add all 3 of the above plus @OFR-IIASA as joint owners of all other costs-related files, replacing @measrainsey.
Also:
- Remove @GamzeUnlu95 from co-ownership of some `.model.material` files, to indicate that @macflo8 is now the only person who can be asked for review.
- Anyone tagged in the issue or added as an owner should mention if these changes do not match their recollection or current capabilities.
- Approve if no objection is heard.

Adjust code owners for `.tools.costs`

---

doc/project/ssp.rst
doc/whatsnew.rst
message_ix_models/project/ssp/cli.py
message_ix_models/project/ssp/transport.py
message_ix_models/tests/project/ssp/test_transport.py
message_ix_models/tools/iamc.py

This PR adds the function `message_ix_models.project.ssp.transport.process_df()` as an entry point to the functionality established in #225 and #259.
cf. [Slack messages](https://iiasa-ece.slack.com/archives/CCFHDNA6P/p1740993729970499)
- Read [the expanded docs](https://iiasa-energy-program-message-ix--303.com.readthedocs.build/projects/models/en/303/project/ssp.html#module-message_ix_models.project.ssp.transport) for the module, in particular the new function.
- Call the function with 'real' input data.
- Report any errors, with detail about the calling code and input data.

Add function entrypoint to `.ssp.transport`

---

message_ix_models/data/material/petrochemicals/petrochemicals_techno_economic.xlsx
message_ix_models/data/material/set.yaml
message_ix_models/model/material/data_ammonia_new.py

**Required:** This PR changes the `level` dimension of hydrogen flows in the refinery sector and fixes the activity of ammonia CCS technologies in 2025 to 0.
**Required:** no review required for merge to ssp-dev.
~~- [ ] Continuous integration checks all ✅~~
~~- [ ] Add or expand tests; coverage checks both ✅~~
~~- [ ] Add, expand, or update documentation.~~
~~- [ ] Update doc/whatsnew.~~

Update refinery hydrogen level and CCS bounds

---

.github/workflows/pytest.yaml
message_ix_models/model/bare.py
message_ix_models/model/disutility.py
message_ix_models/model/material/cli.py
message_ix_models/model/structure.py
message_ix_models/model/transport/build.py
message_ix_models/model/water/data/water_for_ppl.py
message_ix_models/project/edits/__init__.py
message_ix_models/project/ssp/structure.py
message_ix_models/report/operator.py
message_ix_models/tests/model/test_disutility.py
message_ix_models/tests/model/test_macro.py
message_ix_models/tests/model/test_structure.py
message_ix_models/tests/tools/costs/test_gdp.py
message_ix_models/tests/util/test_sdmx.py
message_ix_models/tools/iamc.py
message_ix_models/tools/wb.py
message_ix_models/util/sdmx.py

This PR intends to fix a few things about the Code Quality CI:
- It fixes a typo such that the Code Quality check will consider the changes here, not those already on `main`
- It reduces the complexity of the `cool_tech()` function to below 11, which is our accepted limit here (@adrivinca, this may serve as a template for the future, if you're interested: I have simply extracted one `if/else` clause and moved that to its own function, following the idea that every function should have one clearly defined task)
- I've also deleted the `pre-commit` cache in hopes of it now picking up the latest version of genno, which should fix the mypy errors we've been seeing in the nightly tests
Housekeeping:
- Mirror the 'fix' from khaeru/genno#166 for a mypy error.
- Adjust import of the Annotation …

Fix Code Quality CI: checkout action and complex function

---

.github/workflows/pytest.yaml
message_ix_models/model/transport/testing.py
message_ix_models/tests/model/transport/test_build.py
message_ix_models/tests/model/transport/test_report.py

Work around khaeru/genno#171 by installing dask < 2025.4.0 in the "pytest" CI workflows.
This should resolve failures observed in scheduled/PR runs since that dask version was released on 2025-04-22.
- Note that the CI checks all pass.

Work around khaeru/genno#171

---

message_ix_models/tests/model/material/test_build.py
message_ix_models/tests/util/test_importlib.py
message_ix_models/util/click.py
message_ix_models/util/common.py
message_ix_models/util/importlib.py

Closes #344, thus fixes the "Code quality" check for the `main` branch and other PRs.
Also: a small adjustment to .util.importlib.MessageDataFinder. This is to avoid error messages like [this one](https://github.com/iiasa/message-ix-models/actions/runs/14972200595/job/42055631634#step:11:18):
```
Traceback (most recent call last):
File "/home/runner/work/message-ix-models/message-ix-models/.venv/bin/mix-models", line 4, in <module>
from message_ix_models.cli import main
File "/home/runner/work/message-ix-models/message-ix-models/.venv/lib/python3.13/site-packages/message_ix_models/cli.py", line 204, in <module>
__import__(name)
~~~~~~~~~~^^^^^^
File "/home/runner/work/message-ix-models/message-ix-models/.venv/lib/python3.13/site-packages/message_ix_models/model/material/cli.py", line 29, …
```

Adjust for click v8.2.0

---

doc/whatsnew.rst
message_ix_models/data/emission.yaml
message_ix_models/data/transport/emi-intensity.csv
message_ix_models/project/ssp/transport.py
message_ix_models/tests/project/ssp/test_transport.py

- Add emission intensity values imputed from CEDS data and MESSAGEix-Transport outputs.
- This closes #307.
- Adjust handling of species codes appearing in IAMC 'variable' and 'unit' dimensions in the input/expected output.
Note the CI checks all pass.

Improve aviation emissions postprocessing

---

.github/workflows/pytest.yaml

Parallel to iiasa/ixmp#586 and iiasa/message_ix#962, use a version of Java compatible with JPype1 v1.6.0. This version was released 2025-07-07 and triggered failures of the `windows-latest-py3.13-upstream-*` scheduled testing jobs, for instance [here](https://github.com/iiasa/message-ix-models/actions/runs/16134476513).
Note that the CI checks all pass on the jobs labeled "(pull_request)" (not pull_request_target). → [run #3827](https://github.com/iiasa/message-ix-models/actions/runs/16262060072?pr=370)
- ~Add, expand, or update documentation.~ N/A; CI changes only.

Use Java 21 on Windows GHA runners

---

doc/whatsnew.rst
message_ix_models/project/ssp/transport.py
message_ix_models/tests/model/transport/test_report.py
message_ix_models/tests/project/ssp/test_transport.py

Closes #387.
The initial commits implement the first method described at that issue, from the description of #387. These were made before the method was changed again; the later commits [will] implement the second method.
- Read the diff.
- Note that the CI checks all pass.

Adjust `.ssp.transport` to avoid negative emissions totals

---

doc/index.rst

This PR rearranges the "toctree" (table of contents tree) in the documentation index page and left/navigation sidebar, such that the "conceptual documentation" appears in a new section, that appears second, beneath the user guide.
- Look at [the ReadTheDocs preview build of the documentation](https://iiasa-energy-program-message-ix--416.com.readthedocs.build/projects/models/en/416/).
- Read the index page, particularly:
- The first paragraph.
- The new "Conceptual documentation" section.
- Look at the table of contents on the left side.
- Follow the links to the conceptual docs main page.

Adjust conceptual docs ordering
